### test

### CREATE NEW COIN
POST http://localhost:3000/coins/apply
content-type: application/json

{
    "name": "AAAA",
    "symbol": "1212312",
    "logo": "https://uploads-ssl.webflow.com/619ce4a1ae033d566ff33283/61a220cb6d49682ecaba5506_wagmi-logo-square-black-p-500.png",
    "description": "WAGMI is the brilliant product of combining a Play-To-Earn game concept with a cultural acronym. “What started as a crypto internet meme, is now the official battle cry to save all mankind: WAGMI Defense, the first game of the envisioned franchise, features both versus and story mode, with full MMORPG on the roadmap. The year is 3022; Aliens have discovered the earth’s core contains NiFe, the essential element to the Alien’s survival. The Humans must defend earth, and as they claim victory, they proclaim “WAGMI,” and the gamer player earns tokens. &quot;We're All Gonna Make It!”",
    "desc_cn": "WAGMI是一款将“玩即赚”游戏概念与文化首字母缩略词相结合的优秀产品。“最初是一个加密的互联网迷因，现在是拯救全人类的官方口号：WAGMI Defense，设想中的系列游戏的第一款，以对抗和故事模式为特色，路线图上有完整的MMORPG。今年是3022年；外星人发现地球的核心包含NiFe，这是外星人生存的基本要素。T人类必须保卫地球，当他们宣布胜利时，他们宣布“WAGMI”，玩家将获得代币。“我们都会成功！”\r\n",
    "chain": "ETH",
    "contractAddress": "0x3B6a04174a7ada11720aC0aa1ded011145a5728b612c0d2F100F0",
    "whitelistLink": "PINKSALE",
    "presalePlatform": "PINKSALE",
    "presaleLink": "presaleLink",
    "presaleTime": "2022-12-31 12:00:00",
    "launchTime": "2022-12-31 12:00:00",
    "launchPlatform": "totalVotes",
    "launchLink": "totalVotes",
    "contactEmail": "totalVotes",
    "contactTelegram": "totalVotes",
    "kyc": "totalVotes",
    "approvedKyc": "totalVotes",
    "audit": "totalVotes",
    "approvedAudit": "totalVotes",
    "approvedAt": "totalVotes",
    "website": "totalVotes",
    "discord": "totalVotes",
    "telegram": "totalVotes",
    "twitter": "totalVotes",
    "telegram_cn": "totalVotes",
    "btok": "totalVotes"
}

### FIND ALL
GET http://localhost:3000/coins?chain=ETH&status=APPROVING

### handle upvote
POST http://localhost:3000/coins/tran-van-teo/vote


### TEST COOKIE 
GET http://localhost:3000/coins/cookie


### APPROVED COIN
GET http://localhost:3000/coins/tran-van-teo/approval
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzgzMDczODQtMzExYS00ZTlmLThmZTEtYjBkM2E1YTRlOGM4IiwiZW1haWwiOiJxdWFuZ2hhdTk2MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjZhMGEzMThiY2MzZjMwMmMuMjgxNWZjZjE0ZWFmZDAxMzY3YmQ2MzFhNTY3NDljNjFiMTMzNGZkN2ZkNjU5MDI1ZGYxNzA4MmM3MWQ3NTIyZSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMjItMDktMThUMDU6Mjg6MjguMjIxWiIsInVwZGF0ZWRBdCI6IjIwMjItMDktMThUMDU6Mjg6MjguMjIxWiJ9LCJpYXQiOjE2NjM5OTI4NTIsImV4cCI6MTY2Mzk5MzE1Mn0.Ezu1DOxMBxO3YvVMfl5ijlv2khbzUz1aWf7NT2nV8m8

### add to promoted list
POST http://localhost:3000/coins/tran-van-teo/addPromote
content-type: application/json

{
    "startTime": "2022-12-31",
    "expiredTime": "2022-12-31"
}

### get promoted list
GET http://localhost:3000/coins/promoted


### delete promoted coin in list
DELETE  http://localhost:3000/coins/promoted/tran-van-teo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzgzMDczODQtMzExYS00ZTlmLThmZTEtYjBkM2E1YTRlOGM4IiwiZW1haWwiOiJxdWFuZ2hhdTk2MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjZhMGEzMThiY2MzZjMwMmMuMjgxNWZjZjE0ZWFmZDAxMzY3YmQ2MzFhNTY3NDljNjFiMTMzNGZkN2ZkNjU5MDI1ZGYxNzA4MmM3MWQ3NTIyZSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMjItMDktMThUMDU6Mjg6MjguMjIxWiIsInVwZGF0ZWRBdCI6IjIwMjItMDktMThUMDU6Mjg6MjguMjIxWiJ9LCJpYXQiOjE2NjM5ODY4OTMsImV4cCI6MTY2Mzk4NzE5M30.Z7NpIC1kliaZlAjTBXxC0eP7OvTcafQCvYEtRyfR7r8